apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: "7.0.0"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: podinfo.localhost
          paths:
            - path: /
              pathType: ImplementationSpecific
